# Generated by Django 4.2.4 on 2023-09-01 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_remove_admin_user_admin_is_staff_admin_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
