# Generated by Django 4.2.4 on 2023-09-01 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0014_subject_gradelvl_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='gradelvl_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.gradelevel'),
        ),
    ]
