# Generated by Django 4.2.4 on 2023-09-14 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0015_alter_subject_gradelvl_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='subject_id',
        ),
        migrations.CreateModel(
            name='TeacherAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.department')),
                ('gradelvl_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.gradelevel')),
                ('section_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.section')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.subject')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='teacher',
            name='assignments',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='database.teacherassignment'),
        ),
    ]
