# Generated by Django 4.2.4 on 2023-09-15 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0016_remove_teacher_subject_id_teacherassignment_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeacherAssignment',
            new_name='Assigned',
        ),
        migrations.RenameField(
            model_name='assigned',
            old_name='department_id',
            new_name='dept_id',
        ),
        migrations.RenameField(
            model_name='assigned',
            old_name='teacher_id',
            new_name='teacher',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='assignments',
        ),
    ]
