# Generated by Django 4.2.4 on 2023-09-15 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0017_rename_teacherassignment_assigned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='mname',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
