# Generated by Django 4.2.4 on 2023-09-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0019_alter_teacher_mname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
