# Generated by Django 4.2.4 on 2023-09-20 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0021_alter_assigned_unique_together_studentgrade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentgrade',
            name='assignment_name',
        ),
    ]
